npm install axios@latest
npm install firebase@latest
npm install http2@latest
npm install react-bootstrap@latest
npm install react-dom@latest
npm install react-router-dom@latest
npm install react-scripts@latest
npm install react-slick@latest
npm install react-helmet-async@latest
npm install react-hot-toast@latest
npm install react-image-gallery@latest
npm install web-vitals@latest
