name: Firebase Deploy

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version appropriate for your project

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: npm install&&cd functions&&echo "$ADMIN_SDK">heavy-local-admin.json&&npm install&&cd ..
        env:
          ADMIN_SDK: ${{ secrets.HEAVY_LOCAL_ADMIN }}


      - name: Deploy to Firebase
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON">google-application-credentials.json&&firebase deploy --project heavy-local-12bc4
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          REACT_APP_USE_EMULATORS: ${{ secrets.REACT_APP_USE_EMULATORS }}
          ZONE_ID: ${{ secrets.ZONE_ID }}
          TOKEN: ${{ secrets.TOKEN }}
          REACT_APP_RELEASE: ${{ secrets.REACT_APP_RELEASE }}
          GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_ACCOUNT }}
          CI: false
